const NationalParks = [
  {name: 'Acadia', link: 'acadia'},
  {name: 'American Samoa', link: 'american-samoa'},
  {name: 'Arches', link: 'arches'},
  {name: 'Badlands', link: 'badlands'},
  {name: 'Big Bend', link: 'big-bend'},
  {name: 'Biscayne', link: 'biscayne'},
  {name: 'Black Canyon of the Gunnison', link: 'black-canyon-of-the-gunnison'}, 
  {name: 'Bryce Canyon', link: 'bryce-canyon'},
  {name: 'Canyonlands', link: 'canyonlands'},
  {name: 'Capitol Reef', link: 'capitol-reef'},
  {name: 'Carlsbad Caverns', link: 'carlsbad-caverns'},
  {name: 'Channel Islands', link: 'channel-islands'},
  {name: 'Congaree', link: 'congaree'},
  {name: 'Crater Lake', link: 'crater-lake'},
  {name: 'Cuyahoga Valley', link: 'cuyahoga-valley'},
  {name: 'Death Valley', link: 'death-valley'},
  {name: 'Denali', link: 'denali'},
  {name: 'Dry Tortugas', link: 'dry-tortugas'},
  {name: 'Everglades', link: 'everglades'},
  {name: 'Gates of the Artic', link: 'gates-of-the-artic'},
  {name: 'Glacier', link: 'glacier'},
  {name: 'Glacier Bay', link: 'glacier-bay'},
  {name: 'Grand Canyon', link: 'grand-canyon'},
  {name: 'Grand Teton', link: 'grand-teton'},
  {name: 'Great Basin', link: 'great-basin'},
  {name: 'Great Sand Dunes', link: 'great-sand-dunes'},
  {name: 'Great Smoky Mountains', link: 'great-smoky-mountains'},
  {name: 'Guadalupe Mountains', link: 'guadalupe-mountains'},
  // {name: 'Haleakalā', link: 'haleakala'},
  // {name: 'Hawaiʻi Volcanoes', link: 'hawaii-volcanoes'},
  {name: 'Hot Springs', link: 'hot-springs'},
  {name: 'Isle Royale', link: 'isle-royale'},
  {name: 'Joshua Tree', link: 'joshua-tree'},
  {name: 'Katmai', link: 'katmai'},
  {name: 'Kenai Fjords', link: 'kenai-fjords'},
  {name: 'Kings Canyon', link: 'kings-canyon'},
  {name: 'Kobuk Valley', link: 'kobuk-valley'},
  {name: 'Lake Clark', link: 'lake-clark'},
  {name: 'Lassen Volcanic', link: 'lassen-volcanic'},
  {name: 'Mammoth Cave', link: 'mammoth-cave'},
  {name: 'Mesa Verde', link: 'mesa-verde'},
  {name: 'Mount Rainier', link: 'mount-rainer'},
  {name: 'North Cascades', link: 'north-cascades'},
  {name: 'Olympic', link: 'olympic'},
  {name: 'Petrified Forest', link: 'petrified-forest'},
  {name: 'Pinnacles', link: 'pinnacles'},
  {name: 'Redwood', link: 'redwood'},
  {name: 'Rocky Mountain', link: 'rocky-mountain'},
  {name: 'Saguaro', link: 'saguaro'},
  {name: 'Sequoia', link: 'sequoia'},
  {name: 'Shenandoah', link: 'shenandoah'},
  {name: 'Theodore Roosevelt', link: 'theodore-roosevelt'},
  {name: 'Virgin Islands', link: 'virgin-islands'},
  {name: 'Voyageurs', link: 'voyageurs'},
  {name: 'Wind Cave', link: 'wind-cave'},
  // {name: 'Wrangell-St. Elias', link: 'wrangell-st-elias'},
  {name: 'Yellowstone', link: 'yellowstone'},
  {name: 'Yosemite', link: 'yosemite'},
  {name: 'Zion', link: 'zion'}
];

export default NationalParks;